version: 2
sql:
  - engine: "mysql"
    queries: "query.sql"
    schema: "../../internal/mysql/migrations"
    gen:
      go:
        package: "generated"
        out: "../../internal/mysql/generated"
